#!/bin/sh
# RB2011 как простая точка доступа + свитч
# OpenWrt 19.07.x / 24.x

# ---------- СЕТЬ ----------
# Создаем LAN мост через все порты
uci set network.lan=interface
uci set network.lan.type='br-lan'
uci set network.lan.ifname='eth0.0 eth0.1 eth0.2 eth0.3 eth0.4 eth0.5'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='172.16.0.20'   # статический адрес в твоей сети
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='172.16.0.1'       # шлюз
uci set network.lan.dns='172.16.0.1'     # DNS-сервер
uci commit network

# ---------- DHCP ----------
# Выключаем DHCP, чтобы основной роутер раздавал адреса
uci set dhcp.lan.ignore='1'
uci commit dhcp
/etc/init.d/dnsmasq restart

# ---------- Wi-Fi ----------
# Настройки радиоинтерфейса (2.4 GHz)
SSID="ChikaWiFi"
PASSWORD="irdiS0066"
COUNTRY="RU"
CHANNEL="13"  # подбери свободный канал

opkg update
opkg remove wpad-basic wpad-mini 2>/dev/null
opkg install wpad

uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country="$COUNTRY"
uci set wireless.radio0.channel="$CHANNEL"
uci set wireless.radio0.hwmode='11ng'
uci set wireless.radio0.htmode='HT20'

uci set wireless.@wifi-iface[0].device='radio0'
uci set wireless.@wifi-iface[0].mode='ap'
uci set wireless.@wifi-iface[0].network='lan'
uci set wireless.@wifi-iface[0].ssid="$SSID"
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key="$PASSWORD"

uci set wireless.@wifi-iface[0].disassoc_low_ack='1'  # стабильность для старого AP

uci commit wireless
wifi reload

# ---------- ФИНАЛ ----------
echo "RB2011 настроен как простая точка доступа"
echo "LAN bridge готов, DHCP отключен, Wi-Fi SSID: $SSID"
