#!/bin/sh
set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║          OpenWrt WiFi Setup Wizard                     ║"
echo "║     Соло роутер или Бесшовный роуминг (Multi-AP)      ║"
echo "╚══════════════════════════════════════════════════════════╝"

# ====================== ВВОД ======================
while true; do
    echo "1) Соло роутер"
    echo "2) Основной роутер R1 (роуминг)"
    echo "3) Точка доступа R2 (роуминг)"
    read -r -p "Выбор [1-3]: " mode
    case "$mode" in
        1) TYPE="SOLO"; ROAMING=0; break ;;
        2) TYPE="R1";   ROAMING=1; break ;;
        3) TYPE="R2";   ROAMING=1; break ;;
        *) echo "[!] Неверный выбор" ;;
    esac
done

read -r -p "SSID: " SSID
read -r -p "Пароль (минимум 8): " PASSWORD

if [ "$TYPE" = "R2" ]; then
    read -r -p "IP основного роутера R1 [192.168.1.1]: " R1_IP
    R1_IP=${R1_IP:-192.168.1.1}
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Режим: $TYPE"
echo "Роуминг: $([ "$ROAMING" = "1" ] && echo 'ВКЛЮЧЕН' || echo 'ОТКЛЮЧЕН')"
echo "SSID: $SSID"
[ "$TYPE" = "R2" ] && echo "IP R1: $R1_IP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -r -p "Продолжить? [Y/n]: " y
[ "$y" = "n" ] || [ "$y" = "N" ] && exit 0

# ====================== ПАКЕТЫ ======================
echo "[*] Установка пакетов..."

if command -v apk >/dev/null 2>&1; then
    apk update
    
    echo "[*] Удаляем конфликтующие пакеты wpad..."
    for pkg in wpad-basic wpad-basic-mbedtls wpad-basic-openssl wpad-mini wpad; do
        apk del "$pkg" 2>/dev/null || true
    done
    
    echo "[*] Устанавливаем полную версию wpad..."
    apk add wpad-openssl 2>/dev/null || apk add wpad-mbedtls 2>/dev/null || apk add wpad 2>/dev/null || {
        echo "[!] Ошибка установки wpad"
        exit 1
    }
else
    opkg update
    
    echo "[*] Удаляем конфликтующие пакеты wpad..."
    for pkg in wpad-basic wpad-basic-mbedtls wpad-basic-openssl wpad-mini wpad; do
        opkg remove "$pkg" 2>/dev/null || true
    done
    
    echo "[*] Устанавливаем полную версию wpad..."
    opkg install wpad-openssl 2>/dev/null || opkg install wpad-mbedtls 2>/dev/null || opkg install wpad 2>/dev/null || {
        echo "[!] Ошибка установки wpad"
        exit 1
    }
fi

echo "[✓] Пакеты установлены"

# ====================== СОЗДАНИЕ КОНФИГУРАЦИИ ======================
echo "[*] Создание WiFi конфигурации..."

# Полностью удаляем старую конфигурацию
rm -f /etc/config/wireless

# Определяем физические интерфейсы
PHY_DEVICES=""
if [ -d /sys/class/ieee80211 ]; then
    PHY_DEVICES=$(ls /sys/class/ieee80211/ 2>/dev/null | sort)
fi

if [ -z "$PHY_DEVICES" ]; then
    echo "[!] WiFi устройства не найдены в /sys/class/ieee80211/"
    echo "    Проверьте: ls /sys/class/ieee80211/"
    exit 1
fi

echo "[*] Найдены физические устройства: $PHY_DEVICES"

# Определяем диапазоны
RADIO_24=""
RADIO_5=""
RADIO_24_IDX=""
RADIO_5_IDX=""

for phy in $PHY_DEVICES; do
    phy_idx=$(echo "$phy" | sed 's/phy//')
    
    # Проверяем поддерживаемые диапазоны
    BANDS=$(iw phy${phy_idx} info 2>/dev/null | grep "Band [0-9]:" | awk '{print $2}' | sed 's/://')
    
    if echo "$BANDS" | grep -q "^1$"; then
        RADIO_24="radio${phy_idx}"
        RADIO_24_IDX="$phy_idx"
        echo "[*] phy${phy_idx} → radio${phy_idx} (2.4GHz)"
    fi
    if echo "$BANDS" | grep -q "^2$"; then
        RADIO_5="radio${phy_idx}"
        RADIO_5_IDX="$phy_idx"
        echo "[*] phy${phy_idx} → radio${phy_idx} (5GHz)"
    fi
done

# Если phy поддерживает оба диапазона
if [ "$RADIO_24" = "$RADIO_5" ] && [ -n "$RADIO_24" ]; then
    echo "[*] Одно устройство поддерживает оба диапазона"
fi

echo "  2.4GHz: ${RADIO_24:-не найден}"
echo "  5GHz: ${RADIO_5:-не найден}"

# Параметры
if [ "$TYPE" = "R1" ]; then
    CH24=1; CH5=36
    NAS24="${SSID}_24G_R1"; NAS5="${SSID}_5G_R1"
    MOB_DOMAIN="a1b2"
elif [ "$TYPE" = "R2" ]; then
    CH24=6; CH5=40
    NAS24="${SSID}_24G_R2"; NAS5="${SSID}_5G_R2"
    MOB_DOMAIN="a1b2"
else
    CH24=1; CH5=36
    NAS24=""; NAS5=""
    MOB_DOMAIN=""
fi

# Создаём конфигурацию вручную
cat > /etc/config/wireless << EOF
# WiFi Configuration generated by setup script

EOF

# Добавляем 2.4GHz
if [ -n "$RADIO_24" ]; then
    cat >> /etc/config/wireless << EOF
config wifi-device '${RADIO_24}'
        option type 'mac80211'
        option band '2g'
        option channel '${CH24}'
        option htmode 'HT20'
        option country 'RU'
        option disabled '0'
        option noscan '1'

config wifi-iface 'wifinet0'
        option device '${RADIO_24}'
        option mode 'ap'
        option network 'lan'
        option ssid '${SSID}'
        option encryption 'psk2'
        option key '${PASSWORD}'
        option wmm '1'
        option wpa_group_rekey '3600'
        option isolate '0'
        option disassoc_low_ack '0'
$(if [ "$ROAMING" = "1" ] && [ -n "$NAS24" ]; then
cat << INNER_EOF
        option ieee80211r '1'
        option mobility_domain '${MOB_DOMAIN}'
        option ft_over_ds '1'
        option ft_psk_generate_local '1'
        option nasid '${NAS24}'
        option pmk_r1_push '1'
        option ieee80211k '1'
        option rrm_neighbor_report '1'
        option rrm_beacon_report '1'
        option ieee80211v '1'
        option bss_transition '1'
INNER_EOF
fi)

EOF
fi

# Добавляем 5GHz
if [ -n "$RADIO_5" ]; then
    cat >> /etc/config/wireless << EOF
config wifi-device '${RADIO_5}'
        option type 'mac80211'
        option band '5g'
        option channel '${CH5}'
        option htmode 'VHT80'
        option country 'RU'
        option disabled '0'
        option noscan '1'

config wifi-iface 'wifinet1'
        option device '${RADIO_5}'
        option mode 'ap'
        option network 'lan'
        option ssid '${SSID}'
        option encryption 'psk2'
        option key '${PASSWORD}'
        option wmm '1'
        option wpa_group_rekey '3600'
        option isolate '0'
        option disassoc_low_ack '0'
$(if [ "$ROAMING" = "1" ] && [ -n "$NAS5" ]; then
cat << INNER_EOF
        option ieee80211r '1'
        option mobility_domain '${MOB_DOMAIN}'
        option ft_over_ds '1'
        option ft_psk_generate_local '1'
        option nasid '${NAS5}'
        option pmk_r1_push '1'
        option ieee80211k '1'
        option rrm_neighbor_report '1'
        option rrm_beacon_report '1'
        option ieee80211v '1'
        option bss_transition '1'
INNER_EOF
fi)

EOF
fi

echo "[✓] Конфигурация создана"
echo ""
echo "--- Содержимое /etc/config/wireless ---"
cat /etc/config/wireless
echo "----------------------------------------"

# ====================== СЕТЬ ======================
echo "[*] Настройка сети..."

if [ "$TYPE" = "R2" ]; then
    AP_IP=${AP_IP:-192.168.1.2}
    read -r -p "IP для этой точки доступа [$AP_IP]: " input_ip
    AP_IP=${input_ip:-$AP_IP}
    
    uci set network.lan.ipaddr="$AP_IP"
    uci set network.lan.netmask='255.255.255.0'
    uci set network.lan.gateway="$R1_IP"
    uci set network.lan.dns="$R1_IP"
    uci set dhcp.lan.ignore='1'
    uci commit network
    uci commit dhcp
    
    /etc/init.d/dnsmasq disable 2>/dev/null || true
    /etc/init.d/dnsmasq stop 2>/dev/null || true
    /etc/init.d/firewall disable 2>/dev/null || true
    /etc/init.d/firewall stop 2>/dev/null || true
else
    uci set network.lan.netmask='255.255.255.0'
    uci set dhcp.lan.start='100'
    uci set dhcp.lan.limit='150'
    uci set dhcp.lan.leasetime='12h'
    uci set dhcp.wan.ignore='1'
    uci commit network
    uci commit dhcp
fi

# ====================== ПРИМЕНЕНИЕ ======================
echo "[*] Применение настроек..."
wifi reload 2>&1 || wifi 2>&1

sleep 3

echo ""
echo "[*] Статус WiFi:"
if command -v iwinfo >/dev/null 2>&1; then
    iwinfo 2>/dev/null | grep -E "wlan[0-9]|ESSID|Channel|Mode" || echo "  (интерфейсы не найдены)"
else
    echo "  iwinfo не установлен"
    echo "  Список интерфейсов:"
    ls /sys/class/net/wlan* 2>/dev/null || echo "  (wlan интерфейсы не найдены)"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                    НАСТРОЙКА ЗАВЕРШЕНА                   ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║ SSID:            $SSID                                ║"
echo "║ Режим:           $TYPE                                       ║"
echo "║ Роуминг:         $([ "$ROAMING" = "1" ] && echo 'ВКЛЮЧЕН' || echo 'ОТКЛЮЧЕН')                              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "[✓] Готово!"
